import {
  CreditTransactionType,
  DocumentStatus,
  DocumentType,
  FileType,
  PaymentMethod,
  PaymentStatus,
  PrismaClient,
  StorageProvider,
  SubscriptionStatus,
  UserRole,
  UserStatus,
} from "@prisma/client";
import bcrypt from "bcrypt";
import { access, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const prisma = new PrismaClient();
const demoPassword = "Password@123";
const localDocumentDir = path.resolve(process.cwd(), "uploads", "documents");
const localDocumentPrefix = "local://documents/";

function previewImage(title: string, pageNumber: number) {
  return `https://placehold.co/820x1160/png?text=${encodeURIComponent(`${title} - Trang ${pageNumber}`)}`;
}

function slugify(value: string) {
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/đ/g, "d")
    .replace(/Đ/g, "d")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 90) || "document";
}

function pdfText(value: string) {
  return value.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

function buildSeedPdf(title: string, pageCount: number) {
  const pages = Math.max(1, pageCount);
  const fontObjectId = pages * 2 + 3;
  const objects: string[] = [];
  const pageObjectIds: number[] = [];

  objects[1] = "<< /Type /Catalog /Pages 2 0 R >>";

  for (let index = 0; index < pages; index += 1) {
    const pageObjectId = index * 2 + 3;
    const contentObjectId = index * 2 + 4;
    pageObjectIds.push(pageObjectId);

    const stream = [
      "BT",
      "/F1 18 Tf",
      "72 740 Td",
      `(${pdfText(title)}) Tj`,
      "0 -32 Td",
      "/F1 12 Tf",
      `(Seed document page ${index + 1} of ${pages}) Tj`,
      "0 -24 Td",
      "(This file is generated by prisma/seed.ts so /documents/:id/file can stream a real PDF.) Tj",
      "ET",
    ].join("\n");

    objects[pageObjectId] = [
      "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792]",
      `/Resources << /Font << /F1 ${fontObjectId} 0 R >> >>`,
      `/Contents ${contentObjectId} 0 R >>`,
    ].join(" ");
    objects[contentObjectId] = `<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`;
  }

  objects[2] = `<< /Type /Pages /Kids [${pageObjectIds.map((id) => `${id} 0 R`).join(" ")}] /Count ${pages} >>`;
  objects[fontObjectId] = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>";

  let body = "%PDF-1.4\n";
  const offsets = [0];
  for (let id = 1; id < objects.length; id += 1) {
    if (!objects[id]) continue;
    offsets[id] = Buffer.byteLength(body);
    body += `${id} 0 obj\n${objects[id]}\nendobj\n`;
  }

  const xrefOffset = Buffer.byteLength(body);
  body += `xref\n0 ${objects.length}\n`;
  body += "0000000000 65535 f \n";
  for (let id = 1; id < objects.length; id += 1) {
    body += `${String(offsets[id] ?? 0).padStart(10, "0")} 00000 n \n`;
  }
  body += `trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`;

  return Buffer.from(body, "utf8");
}

async function writeSeedDocumentFile(title: string, pageCount: number) {
  await mkdir(localDocumentDir, { recursive: true });
  const filename = `seed-${slugify(title)}.pdf`;
  const buffer = buildSeedPdf(title, pageCount);
  await writeFile(path.join(localDocumentDir, filename), buffer);
  return {
    filename,
    fileUrl: `${localDocumentPrefix}${encodeURIComponent(filename)}`,
    fileSize: buffer.length,
  };
}

async function localDocumentExists(fileUrl: string) {
  if (!fileUrl.startsWith(localDocumentPrefix)) return false;
  const filename = decodeURIComponent(fileUrl.slice(localDocumentPrefix.length));
  try {
    await access(path.join(localDocumentDir, filename));
    return true;
  } catch {
    return false;
  }
}

async function seedUsers() {
  const passwordHash = await bcrypt.hash(demoPassword, 10);

  const users = [
    {
      email: "admin@hoclieu.local",
      fullName: "Quan tri HocLieu",
      role: UserRole.ADMIN,
      creditBalance: 100,
    },
    {
      email: "student@hoclieu.local",
      fullName: "Nguyen Van An",
      role: UserRole.USER,
      creditBalance: 20,
    },
    {
      email: "premium@hoclieu.local",
      fullName: "Tran Minh Chau",
      role: UserRole.USER,
      creditBalance: 5,
    },
    {
      email: "credituser@hoclieu.local",
      fullName: "Le Hoang Nam",
      role: UserRole.USER,
      creditBalance: 3,
    },
    {
      email: "newstudent@hoclieu.local",
      fullName: "Pham Thu Ha",
      role: UserRole.USER,
      creditBalance: 0,
    },
  ];

  const seeded = await Promise.all(
    users.map((user) =>
      prisma.user.upsert({
        where: { email: user.email },
        update: {
          fullName: user.fullName,
          passwordHash,
          status: UserStatus.ACTIVE,
          role: user.role,
          creditBalance: user.creditBalance,
        },
        create: {
          fullName: user.fullName,
          email: user.email,
          passwordHash,
          status: UserStatus.ACTIVE,
          role: user.role,
          creditBalance: user.creditBalance,
        },
      }),
    ),
  );

  return Object.fromEntries(seeded.map((user) => [user.email, user]));
}

async function seedCatalog() {
  const schoolEntries = [
    { name: "Dai hoc Bach Khoa", slug: "dai-hoc-bach-khoa" },
    { name: "Dai hoc Kinh te", slug: "dai-hoc-kinh-te" },
    { name: "Dai hoc FPT", slug: "dai-hoc-fpt" },
    { name: "Dai hoc Ngoai thuong", slug: "dai-hoc-ngoai-thuong" },
    { name: "Hoc vien Cong nghe Buu chinh Vien thong", slug: "hoc-vien-cong-nghe-buu-chinh-vien-thong" },
    { name: "Dai hoc Khoa hoc Tu nhien", slug: "dai-hoc-khoa-hoc-tu-nhien" },
    { name: "Dai hoc Su pham Ky thuat TP HCM", slug: "dai-hoc-su-pham-ky-thuat-tp-hcm" },
  ];

  const schools = await Promise.all(
    schoolEntries.map((school) =>
      prisma.school.upsert({
        where: { slug: school.slug },
        update: { name: school.name, deletedAt: null },
        create: school,
      }),
    ),
  );
  const schoolBySlug = Object.fromEntries(schools.map((school) => [school.slug, school]));

  const subjectEntries = [
    { schoolSlug: "dai-hoc-bach-khoa", name: "Cau truc du lieu", slug: "cau-truc-du-lieu" },
    { schoolSlug: "dai-hoc-bach-khoa", name: "Co so du lieu", slug: "co-so-du-lieu" },
    { schoolSlug: "dai-hoc-bach-khoa", name: "Mang may tinh", slug: "bach-khoa-mang-may-tinh" },
    { schoolSlug: "dai-hoc-kinh-te", name: "Xac suat thong ke", slug: "xac-suat-thong-ke" },
    { schoolSlug: "dai-hoc-kinh-te", name: "Marketing", slug: "marketing" },
    { schoolSlug: "dai-hoc-kinh-te", name: "Quan tri kinh doanh", slug: "quan-tri-kinh-doanh" },
    { schoolSlug: "dai-hoc-fpt", name: "Lap trinh Web", slug: "lap-trinh-web" },
    { schoolSlug: "dai-hoc-fpt", name: "Tri tue nhan tao", slug: "tri-tue-nhan-tao" },
    { schoolSlug: "dai-hoc-ngoai-thuong", name: "Tieng Anh", slug: "tieng-anh" },
    { schoolSlug: "hoc-vien-cong-nghe-buu-chinh-vien-thong", name: "Lap trinh huong doi tuong", slug: "ptit-lap-trinh-huong-doi-tuong" },
    { schoolSlug: "hoc-vien-cong-nghe-buu-chinh-vien-thong", name: "An toan thong tin", slug: "ptit-an-toan-thong-tin" },
    { schoolSlug: "dai-hoc-khoa-hoc-tu-nhien", name: "Dai so tuyen tinh", slug: "dai-so-tuyen-tinh" },
    { schoolSlug: "dai-hoc-su-pham-ky-thuat-tp-hcm", name: "He dieu hanh", slug: "he-dieu-hanh" },
  ];

  const subjects = await Promise.all(
    subjectEntries.map((subject) =>
      prisma.subject.upsert({
        where: { slug: subject.slug },
        update: {
          schoolId: schoolBySlug[subject.schoolSlug].id,
          name: subject.name,
          deletedAt: null,
        },
        create: {
          schoolId: schoolBySlug[subject.schoolSlug].id,
          name: subject.name,
          slug: subject.slug,
        },
      }),
    ),
  );

  return {
    schools: schoolBySlug,
    subjects: Object.fromEntries(subjects.map((subject) => [subject.slug, subject])),
  };
}

async function seedPlans() {
  const plans = [
    { name: "Co ban", price: 49000, durationDays: 30, downloadLimit: 20, description: "Phu hop cho nhu cau doc tai lieu hang thang." },
    { name: "Sinh vien", price: 99000, durationDays: 90, downloadLimit: 100, description: "Goi tiet kiem cho mot hoc phan." },
    { name: "Hoc ky", price: 169000, durationDays: 180, downloadLimit: 300, description: "Truy cap dai han cho ca hoc ky." },
  ];

  const seeded = [];
  for (const plan of plans) {
    const existing = await prisma.subscriptionPlan.findFirst({ where: { name: plan.name } });
    if (existing) {
      seeded.push(await prisma.subscriptionPlan.update({ where: { id: existing.id }, data: { ...plan, isActive: true } }));
    } else {
      seeded.push(await prisma.subscriptionPlan.create({ data: plan }));
    }
  }
  return Object.fromEntries(seeded.map((plan) => [plan.name, plan]));
}

type DocumentSeed = {
  title: string;
  description: string;
  uploaderId: number;
  schoolId?: number | null;
  subjectId?: number | null;
  requestedSchoolName?: string | null;
  requestedSubjectName?: string | null;
  documentType: DocumentType;
  status: DocumentStatus;
  pages: number;
  downloads: number;
  fileType?: FileType;
  storageProvider?: StorageProvider;
  approvedBy?: number | null;
  rejectReason?: string | null;
  previewCount?: number;
};

async function upsertDocument(document: DocumentSeed) {
  const existing = await prisma.document.findFirst({
    where: { title: document.title },
    orderBy: { id: "asc" },
  });

  const isApproved = document.status === DocumentStatus.APPROVED;
  const data = {
    schoolId: document.schoolId ?? null,
    subjectId: document.subjectId ?? null,
    requestedSchoolName: document.requestedSchoolName ?? null,
    requestedSubjectName: document.requestedSubjectName ?? null,
    title: document.title,
    description: document.description,
    documentType: document.documentType,
    status: document.status,
    downloadCount: document.downloads,
    viewCount: document.downloads * 3,
    approvedBy: isApproved ? document.approvedBy ?? null : null,
    approvedAt: isApproved ? new Date("2026-06-01T08:00:00.000Z") : null,
    rejectReason: document.rejectReason ?? null,
  };
  const fileType = document.fileType ?? FileType.PDF;
  const localFile = await writeSeedDocumentFile(document.title, document.pages);
  const file = {
    fileUrl: localFile.fileUrl,
    originalFilename: localFile.filename,
    fileType,
    fileSize: localFile.fileSize,
    totalPages: document.pages,
    storageProvider: StorageProvider.LOCAL,
  };

  const saved = existing
    ? await prisma.document.update({
        where: { id: existing.id },
        data: {
          ...data,
          documentFile: {
            upsert: {
              update: file,
              create: file,
            },
          },
        },
      })
    : await prisma.document.create({
        data: {
          uploaderId: document.uploaderId,
          ...data,
          documentFile: { create: file },
        },
      });

  await prisma.documentPreview.deleteMany({ where: { documentId: saved.id } });
  const previewCount = Math.min(document.previewCount ?? 3, document.pages);
  if (previewCount > 0) {
    await prisma.documentPreview.createMany({
      data: Array.from({ length: previewCount }, (_, index) => ({
        documentId: saved.id,
        pageNumber: index + 1,
        imageUrl: previewImage(document.title, index + 1),
        isBlurred: false,
      })),
    });
  }

  return saved;
}

async function seedDocuments(
  users: Awaited<ReturnType<typeof seedUsers>>,
  catalogs: Awaited<ReturnType<typeof seedCatalog>>,
) {
  const admin = users["admin@hoclieu.local"];
  const student = users["student@hoclieu.local"];
  const premium = users["premium@hoclieu.local"];
  const creditUser = users["credituser@hoclieu.local"];
  const newStudent = users["newstudent@hoclieu.local"];
  const schools = catalogs.schools;
  const subjects = catalogs.subjects;

  const documents: DocumentSeed[] = [
    {
      title: "Giai thuat va cau truc du lieu can ban",
      description: "Tong hop cay, do thi va cac thuat toan sap xep.",
      uploaderId: student.id,
      schoolId: schools["dai-hoc-bach-khoa"].id,
      subjectId: subjects["cau-truc-du-lieu"].id,
      documentType: DocumentType.LECTURE,
      status: DocumentStatus.APPROVED,
      pages: 84,
      downloads: 1250,
      approvedBy: admin.id,
    },
    {
      title: "De thi cuoi ky Xac suat thong ke 2025",
      description: "Bo de on tap kem dap an tham khao.",
      uploaderId: student.id,
      schoolId: schools["dai-hoc-kinh-te"].id,
      subjectId: subjects["xac-suat-thong-ke"].id,
      documentType: DocumentType.EXAM,
      status: DocumentStatus.APPROVED,
      pages: 18,
      downloads: 930,
      approvedBy: admin.id,
    },
    {
      title: "Tom tat Lap trinh Web voi React",
      description: "Ghi chu component, hooks va quan ly trang thai.",
      uploaderId: premium.id,
      schoolId: schools["dai-hoc-fpt"].id,
      subjectId: subjects["lap-trinh-web"].id,
      documentType: DocumentType.NOTE,
      status: DocumentStatus.APPROVED,
      pages: 42,
      downloads: 720,
      approvedBy: admin.id,
    },
    {
      title: "Bai tap thuc hanh Co so du lieu",
      description: "Mo hinh quan he, SQL truy van va chuan hoa du lieu.",
      uploaderId: student.id,
      schoolId: schools["dai-hoc-bach-khoa"].id,
      subjectId: subjects["co-so-du-lieu"].id,
      documentType: DocumentType.ASSIGNMENT,
      status: DocumentStatus.APPROVED,
      pages: 35,
      downloads: 488,
      approvedBy: admin.id,
    },
    {
      title: "De cuong Marketing can ban",
      description: "Kien thuc trong tam va cau hoi on thi.",
      uploaderId: premium.id,
      schoolId: schools["dai-hoc-kinh-te"].id,
      subjectId: subjects.marketing.id,
      documentType: DocumentType.LECTURE,
      status: DocumentStatus.APPROVED,
      pages: 56,
      downloads: 614,
      approvedBy: admin.id,
    },
    {
      title: "Tai lieu tham khao Tieng Anh hoc thuat",
      description: "Mau viet luan va tu vung theo chu de.",
      uploaderId: creditUser.id,
      schoolId: schools["dai-hoc-ngoai-thuong"].id,
      subjectId: subjects["tieng-anh"].id,
      documentType: DocumentType.OTHER,
      status: DocumentStatus.APPROVED,
      pages: 67,
      downloads: 301,
      approvedBy: admin.id,
    },
    {
      title: "Lap trinh huong doi tuong voi Java",
      description: "Tong quan class, interface, ke thua va da hinh.",
      uploaderId: student.id,
      schoolId: schools["hoc-vien-cong-nghe-buu-chinh-vien-thong"].id,
      subjectId: subjects["ptit-lap-trinh-huong-doi-tuong"].id,
      documentType: DocumentType.LECTURE,
      status: DocumentStatus.APPROVED,
      pages: 72,
      downloads: 412,
      approvedBy: admin.id,
    },
    {
      title: "Mang may tinh - cau hoi trac nghiem",
      description: "Bo cau hoi on tap TCP/IP, routing va subnetting.",
      uploaderId: premium.id,
      schoolId: schools["dai-hoc-bach-khoa"].id,
      subjectId: subjects["bach-khoa-mang-may-tinh"].id,
      documentType: DocumentType.EXAM,
      status: DocumentStatus.APPROVED,
      pages: 26,
      downloads: 266,
      approvedBy: admin.id,
    },
    {
      title: "Dai so tuyen tinh - cong thuc nhanh",
      description: "Ma tran, dinh thuc, khong gian vector va tri rieng.",
      uploaderId: creditUser.id,
      schoolId: schools["dai-hoc-khoa-hoc-tu-nhien"].id,
      subjectId: subjects["dai-so-tuyen-tinh"].id,
      documentType: DocumentType.NOTE,
      status: DocumentStatus.APPROVED,
      pages: 31,
      downloads: 144,
      approvedBy: admin.id,
    },
    {
      title: "Ho so moi can duyet - Phan tich nghiep vu",
      description: "Tai lieu do user nhap truong va mon chua co trong DB.",
      uploaderId: newStudent.id,
      requestedSchoolName: "Dai hoc Mo Ha Noi",
      requestedSubjectName: "Phan tich nghiep vu",
      documentType: DocumentType.LECTURE,
      status: DocumentStatus.PENDING,
      pages: 24,
      downloads: 0,
      previewCount: 5,
    },
    {
      title: "Bai nop cho truong moi - Kiem thu phan mem",
      description: "Tai lieu pending de admin test luong tu tao truong mon khi duyet.",
      uploaderId: newStudent.id,
      requestedSchoolName: "Dai hoc Cong nghe Sai Gon",
      requestedSubjectName: "Kiem thu phan mem",
      documentType: DocumentType.ASSIGNMENT,
      status: DocumentStatus.PENDING,
      pages: 19,
      downloads: 0,
      previewCount: 5,
    },
    {
      title: "Tai lieu bi tu choi vi thieu nguon",
      description: "Ban ghi mau cho trang quan tri tai lieu bi tu choi.",
      uploaderId: newStudent.id,
      schoolId: schools["dai-hoc-fpt"].id,
      subjectId: subjects["tri-tue-nhan-tao"].id,
      documentType: DocumentType.OTHER,
      status: DocumentStatus.REJECTED,
      pages: 12,
      downloads: 0,
      rejectReason: "Noi dung chua co nguon tham khao ro rang.",
    },
  ];

  const saved = [];
  for (const document of documents) {
    saved.push(await upsertDocument(document));
  }
  return Object.fromEntries(saved.map((document) => [document.title, document]));
}

async function seedSubscriptionsAndPayments(
  users: Awaited<ReturnType<typeof seedUsers>>,
  plans: Awaited<ReturnType<typeof seedPlans>>,
) {
  const premiumUser = users["premium@hoclieu.local"];
  const plan = plans["Sinh vien"];
  const startDate = new Date("2026-06-01T00:00:00.000Z");
  const endDate = new Date("2026-08-30T00:00:00.000Z");

  const existingSubscription = await prisma.subscription.findFirst({
    where: { userId: premiumUser.id, planId: plan.id, status: SubscriptionStatus.ACTIVE },
  });
  if (existingSubscription) {
    await prisma.subscription.update({
      where: { id: existingSubscription.id },
      data: { startDate, endDate, status: SubscriptionStatus.ACTIVE },
    });
  } else {
    await prisma.subscription.create({
      data: { userId: premiumUser.id, planId: plan.id, startDate, endDate, status: SubscriptionStatus.ACTIVE },
    });
  }

  const existingPayment = await prisma.payment.findFirst({
    where: { userId: premiumUser.id, planId: plan.id, method: PaymentMethod.MOCK, status: PaymentStatus.PAID },
  });
  if (existingPayment) {
    await prisma.payment.update({
      where: { id: existingPayment.id },
      data: { amount: plan.price, paidAt: startDate },
    });
  } else {
    await prisma.payment.create({
      data: {
        userId: premiumUser.id,
        planId: plan.id,
        amount: plan.price,
        method: PaymentMethod.MOCK,
        status: PaymentStatus.PAID,
        paidAt: startDate,
      },
    });
  }
}

async function seedActivity(
  users: Awaited<ReturnType<typeof seedUsers>>,
  documents: Awaited<ReturnType<typeof seedDocuments>>,
) {
  const creditUser = users["credituser@hoclieu.local"];
  const student = users["student@hoclieu.local"];
  const unlocked = documents["Giai thuat va cau truc du lieu can ban"];
  const liked = documents["De cuong Marketing can ban"];

  await prisma.creditTransaction.upsert({
    where: {
      userId_documentId_type: {
        userId: creditUser.id,
        documentId: unlocked.id,
        type: CreditTransactionType.USE_DOWNLOAD,
      },
    },
    update: { amount: -1 },
    create: {
      userId: creditUser.id,
      documentId: unlocked.id,
      type: CreditTransactionType.USE_DOWNLOAD,
      amount: -1,
    },
  });

  await prisma.download.upsert({
    where: { userId_documentId: { userId: creditUser.id, documentId: unlocked.id } },
    update: { downloadedAt: new Date("2026-06-02T10:00:00.000Z") },
    create: { userId: creditUser.id, documentId: unlocked.id, downloadedAt: new Date("2026-06-02T10:00:00.000Z") },
  });

  await prisma.documentView.upsert({
    where: { userId_documentId: { userId: creditUser.id, documentId: unlocked.id } },
    update: { viewedAt: new Date("2026-06-02T09:30:00.000Z") },
    create: { userId: creditUser.id, documentId: unlocked.id, viewedAt: new Date("2026-06-02T09:30:00.000Z") },
  });

  await prisma.documentReaction.upsert({
    where: { userId_documentId: { userId: student.id, documentId: liked.id } },
    update: { type: "LIKE" },
    create: { userId: student.id, documentId: liked.id, type: "LIKE" },
  });
}

async function repairMissingDocumentFiles() {
  const files = await prisma.documentFile.findMany({
    include: { document: { select: { title: true } } },
  });

  for (const file of files) {
    if (await localDocumentExists(file.fileUrl)) continue;

    const localFile = await writeSeedDocumentFile(file.document.title, file.totalPages ?? 3);
    await prisma.documentFile.update({
      where: { id: file.id },
      data: {
        fileUrl: localFile.fileUrl,
        originalFilename: localFile.filename,
        fileType: FileType.PDF,
        fileSize: localFile.fileSize,
        storageProvider: StorageProvider.LOCAL,
      },
    });
  }
}

async function main() {
  const users = await seedUsers();
  const catalogs = await seedCatalog();
  const plans = await seedPlans();
  const documents = await seedDocuments(users, catalogs);
  await repairMissingDocumentFiles();
  await seedSubscriptionsAndPayments(users, plans);
  await seedActivity(users, documents);

  console.log("Seed completed.");
  console.log(`Admin: admin@hoclieu.local / ${demoPassword}`);
  console.log(`User: student@hoclieu.local / ${demoPassword}`);
  console.log(`Premium user: premium@hoclieu.local / ${demoPassword}`);
  console.log(`Credit user: credituser@hoclieu.local / ${demoPassword}`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
